### PR TITLE
Added the Teams Section

### PR DESCRIPTION
**Pull request by samyak112**
I have added the umbrella on Hover , but it isn't perfect right now. 
umbrella

### CODE REVIEW

**Comment by samyak112** [comment]
Should I add the umbrella as a png?

**Comment by Hiten1708** [comment]
Can you try replacing it with svg? Also, could you show me the mobile view of this site please?

**Comment by samyak112** [comment]
I tried to copy the svg from figma but it copies a black box instead of the
desired image , and about the responsiveness i checked it in responsive
mode and i thought that the whole page wasn't responsive yet so i didn't
made it responsive yet but i can

**Comment by Hiten1708** [comment]
No worries! Try selecting the image from left side panel and ensure it's correct image that you're exporting or else you can also ask Shion (Design lead) to provide you the higher resolution image. 

It's okay if you haven't made it responsive yet. Try doing it when you can and push the commit to your branch and it will automatically be added to this PR. If you're not sure if you have time for that then let me know.

**Comment by samyak112** [comment]
No no I'll do it by tommorow, both of them

**Comment by Hiten1708** [comment]
That's great! Thank you so much :)

**Comment by samyak112** [comment]
Made the changes you can check them out now.

**Comment by Hiten1708** [comment]
Thanks for changing it so quickly. Can u send me a screenshot of mobile view please?

**Comment by Hiten1708** [comment]
Hey, sorry, we made some changes recently to the main branch so, can you pull the changes from main branch and commit again?

**Comment by samyak112** [comment]
> Hey, sorry, we made some changes recently to the main branch so, can you pull the changes from main branch and commit again?
> 

So do i have to clone the new one back to my machine now?

**Comment by Hiten1708** [comment]
Nope, I think you can pull the changes in this PR. :)

**Comment by samyak112** [comment]
Sorry but I don't really know how to do that, can you help me with that?

**Comment by samyak112** [comment]
Thanks, but sorry I don't really use discord , can you just brief the steps here? It will be a great help.
Thank you.

**Comment by samyak112** [comment]
Can any one help me on how to pull the changes from main branch and commit again??

**Comment by Hiten1708** [comment]
> Can any one help me on how to pull the changes from main branch and commit again??

Sorry for late response. You can use this code to get the changes from the main branch. [For more details](https://stackoverflow.com/questions/64155911/get-latest-updates-from-master-into-my-branch)

```
git pull origin main 
```
Please make sure you are using VS Code as that will make it easier to resolve the conficts created by the merge. After that you can push your changes to PR by using this command in terminal (Replacing <your-branch-name> with your branch name)

```
git push -u origin <your-branch-name>
```

**Comment by samyak112** [comment]
Hey, I have committed again with all the changes , but GitHub was not letting me make changes in app.js to add the path of Teams component so I haven't added it.
Thank you

**Comment by samyak112** [comment]
This is how it looks right now 
image

**Comment by samyak112** [comment]
Can anyone please Review this?

**Pull request merged**
