### PR TITLE
Closes #[7]

### PR DESCRIPTION
**Pull request by Owen-Tam**
Contact us section is now responsive

### CODE REVIEW

**Comment by Owen-Tam** [comment]
This is ready for review

**Comment by Hiten1708** [comment]
The code looks good can you confirm it with a screenshot if what it looks like in your localhost?

**Comment by Owen-Tam** [comment]
> The code looks good can you confirm it with a screenshot, what it looks like in your localhost? Edit: Both in desktop and mobile view
Sure
image
image

**Review by Hiten1708 — APPROVED** [review]
Looks good!, require one more approval.

**Pull request merged**
